Repository Intersmash/intersmash, pull requests merged in 2024-09, with the labels that each got.

#191 [issue 190] - Fix InfinispanOperatorProvisionerTest in order not to use .spec.service.type=cache and .spec.autoscale
  testsuite/integration-tests/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/InfinispanOperatorProvisionerTest.java
Labels: it-passed

#192 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#194 [issue 193] - Fix the KafkaOperatorprovisionerTest
  docs/Operator-Based-Provisioning.md
  docs/Provisioner-by-Product.md
  docs/XTF-Configuration-Properties.md
  provisioners/src/main/java/org/jboss/intersmash/application/openshift/KafkaOperatorApplication.java
Labels: it-passed

#180 Polishing the `core` module by adding missing Javadoc and do some refactoring
  core/src/main/java/org/jboss/intersmash/annotations/Intersmash.java
  core/src/main/java/org/jboss/intersmash/annotations/Service.java
  core/src/main/java/org/jboss/intersmash/annotations/Services.java
  core/src/main/java/org/jboss/intersmash/junit5/IntersmashExecutionCondition.java
  core/src/main/java/org/jboss/intersmash/junit5/IntersmashExtension.java
  core/src/main/java/org/jboss/intersmash/provision/Provisioner.java
  core/src/main/java/org/jboss/intersmash/provision/ProvisionerFactory.java
  core/src/main/java/org/jboss/intersmash/provision/ProvisionerManager.java
  core/src/main/java/org/jboss/intersmash/provision/openshift/FailFastUtils.java
  core/src/main/java/org/jboss/intersmash/provision/openshift/OpenShiftUtils.java
  core/src/main/java/org/jboss/intersmash/provision/openshift/WaitersUtil.java
  core/src/main/java/org/jboss/intersmash/provision/openshift/operator/resources/CatalogSource.java
  core/src/main/java/org/jboss/intersmash/provision/openshift/operator/resources/Subscription.java
  core/src/main/java/org/jboss/intersmash/util/CommandLineBasedKeystoreGenerator.java
  core/src/main/java/org/jboss/intersmash/util/ProcessKeystoreGenerator.java
  core/src/main/resources/META-INF/services/org.jboss.intersmash.provision.ProvisionerFactory
  provisioners/README.md
  provisioners/src/main/java/org/jboss/intersmash/application/auto/AutoProvisioningExecutionException.java
  provisioners/src/main/java/org/jboss/intersmash/application/openshift/AutoProvisioningOpenShiftApplication.java
  provisioners/src/main/java/org/jboss/intersmash/provision/auto/AutoProvisioningManagedException.java
  provisioners/src/main/java/org/jboss/intersmash/provision/openshift/auto/OpenShiftAutoProvisioner.java
  provisioners/src/main/java/org/jboss/intersmash/provision/openshift/auto/OpenShiftAutoProvisionerFactory.java
  provisioners/src/main/resources/META-INF/services/org.jboss.intersmash.provision.ProvisionerFactory
  testsuite/integration-tests/src/test/java/org/jboss/intersmash/testsuite/provision/openshift/OpenShiftProvisionerTestBase.java
Labels: documentation, enhancement, it-passed

#204 Improve GETTING_STARTED.md
  docs/GETTING_STARTED.md
Labels: documentation

#203 Removed the method CommandLineBasedKeystoreGenerator::getSplitCommand…
  core/src/main/java/org/jboss/intersmash/util/CommandLineBasedKeystoreGenerator.java
Labels: it-passed, lgtm
